- name: Launch ec2 instance
  connection: local
  hosts: local
  gather_facts: false

  tasks:
    - name: Launch ec2 instance
      ec2:
        key_name: amazon-us-west-2
        group: pymash
        instance_type: "{{ instance_type }}"
        image: ami-7f43f307
        wait: true
        assign_public_ip: true
        vpc_subnet_id: subnet-8c0e2aea
        region: us-west-2
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 15
            delete_on_termination: true
      register: ec2

    - debug:
        msg: "created instance with ip {{ ec2.instances[0].public_ip }}"
