- hosts: all
  become: true
  vars:
    css_sha1: "{{ lookup('pipe', 'shasum ../src/pymash/templates/static/pymash.css').split()[0] }}"
    css_s3_key: "pymash-{{ css_sha1 }}.css"
    css_url: "http://s3.eu-central-1.amazonaws.com/pymash/{{ css_s3_key }}"
  tasks:
    - name: Ensure python3.6 is installed
      command: amazon-linux-extras install python3 creates=/usr/bin/python3.6

    - name: Install git
      yum: name=git state=present

    - name: Install pymash & dependencies
      pip:
        executable: pip3.6
        name: git+https://github.com/alexandershov/pymash@master

    - name: Ensure /etc/pymash.d directory is present
      file: path=/etc/pymash.d state=directory

    - name: Copy environment template
      template: src=/usr/local/etc/pymash/environment dest=/etc/pymash.d/environment

    - name: Uploading css to S3
      aws_s3:
        region: eu-central-1
        bucket: pymash
        object: "{{ css_s3_key }}"
        src: ../src/pymash/templates/static/pymash.css
        mode: put
        permission: public-read
      delegate_to: localhost
      become: false
      when: "'web' in group_names"

    - name: Copy pymash_web@.service file
      copy: src=pymash_web@.service dest=/etc/systemd/system
      when: "'web' in group_names"

    - name: Reloading systemd
      command: systemctl daemon-reload
      when: "'web' in group_names"

    - name: Stopping pymash_web
      command: systemctl stop pymash_web@*
      when: "'web' in group_names"

    - name: Restart pymash_web
      systemd:
        name: "pymash_web@{{ port }}"
        state: restarted
        enabled: true
        daemon-reload: true
      when: "'web' in group_names"
      with_items:
        - 8000
        - 9000
      loop_control:
        loop_var: port

    - name: Copy pymash_background.service file
      copy: src=pymash_background.service dest=/etc/systemd/system
      when: "'background' in group_names"

    - name: Restart pymash_background
      systemd:
        name: pymash_background
        state: restarted
        enabled: true
        daemon-reload: true
      when: "'background' in group_names"

    - name: Copy pymash_monitoring.service file
      copy: src=pymash_monitoring.service dest=/etc/systemd/system
      when: "'background' in group_names"

    - name: Copy pymash_monitoring.timer file
      copy: src=pymash_monitoring.timer dest=/etc/systemd/system
      when: "'background' in group_names"

    - name: Restart pymash_monitoring.timer
      systemd:
        name: pymash_monitoring.timer
        state: restarted
        enabled: true
        daemon-reload: true
      when: "'background' in group_names"
